[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["openai", "@netlify/blobs"]

# (Optional) increase function timeout if you like
#[functions."chat"]
#  timeout = 20
